import React, { useEffect, useRef } from 'react';
import { useStore } from '../../store/useStore';
import { curM, fmt, fmtS, getMonthNameAr, getMonthNameEn } from '../../utils/format';
import { Chart, registerables } from 'chart.js';

Chart.register(...registerables);

export default function ReportScreen() {
  const { cats, budgets, transactions, income, email } = useStore();
  const m = curM();
  const txs = transactions.filter(t => t.date.startsWith(m));
  const eInc = txs.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0);
  const totInc = income + eInc;
  const spent = txs.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
  const net = totInc - spent;

  const sc = {};
  txs.filter(t => t.type === 'expense').forEach(t => {
    sc[t.category] = (sc[t.category] || 0) + t.amount;
  });

  const sorted = Object.entries(sc).sort((a, b) => b[1] - a[1]);

  const ins = [];
  cats.forEach(c => {
    const lim = budgets[c.id] || 0;
    const sp = sc[c.id] || 0;
    if (lim > 0 && sp > lim * 1.15) {
      ins.push({ c: 'var(--red)', t: `"${c.en}/${c.ar}": ${Math.round(((sp - lim) / lim) * 100)}% over budget / فوق الميزانية` });
    }
  });

  const ss = sc['save'] || 0;
  const sl = budgets['save'] || 0;
  if (sl > 0) {
    ins.push({ c: ss >= sl ? 'var(--teal)' : 'var(--amber)', t: `Savings: ${Math.round((ss / sl) * 100)}% of target / الادخار ${Math.round((ss / sl) * 100)}% من الهدف` });
  }

  sorted.forEach(([id, amt]) => {
    const ct = txs.filter(t => t.category === id);
    const cm = cats.find(c => c.id === id);
    if (ct.length >= 5 && spent > 0) {
      ins.push({ c: 'var(--purple)', t: `${cm?.en || id}: ${ct.length} transactions = ${fmt(amt)} EGP (${Math.round((amt / spent) * 100)}% of total)` });
    }
  });

  const chartRef = useRef(null);
  const chartInst = useRef(null);

  useEffect(() => {
    if (sorted.length > 0 && chartRef.current) {
      if (chartInst.current) chartInst.current.destroy();

      const labels = sorted.map(([id]) => cats.find(c => c.id === id)?.en || id);
      const data = sorted.map(([, v]) => v);
      const colors = sorted.map(([id]) => cats.find(c => c.id === id)?.c || '#888');

      chartInst.current = new Chart(chartRef.current, {
        type: 'doughnut',
        data: {
          labels,
          datasets: [{ data, backgroundColor: colors.map(c => c + 'cc'), borderColor: colors, borderWidth: 1.5, hoverBorderWidth: 2.5 }]
        },
        options: {
          responsive: true, maintainAspectRatio: false, cutout: '62%',
          plugins: {
            legend: { display: true, position: 'bottom', labels: { color: 'rgba(240,238,255,.6)', font: { size: 11, family: 'Cairo' }, padding: 12, boxWidth: 10, boxHeight: 10, borderRadius: 5 } },
            tooltip: { callbacks: { label: ctx => `${ctx.label}: ${fmt(ctx.parsed)} ج (${Math.round((ctx.parsed / spent) * 100)}%)` }, bodyFont: { family: 'Cairo' }, titleFont: { family: 'Cairo' } }
          },
          animation: { animateScale: true, duration: 800 }
        }
      });
    }

    return () => {
      if (chartInst.current) chartInst.current.destroy();
    };
  }, [sorted, spent, cats]);

  const handleExport = () => {
    const d = new Date();
    const ml = `${getMonthNameEn()} ${d.getFullYear()} — ${getMonthNameAr()}`;
    let body = `THARA FINANCIAL REPORT — تقرير ثروة المالي\n`;
    body += `${ml}\n${'═'.repeat(50)}\n\n`;
    body += `📊 SUMMARY / الملخص\n${'-'.repeat(30)}\n`;
    body += `Income / الدخل:     ${fmt(totInc)} EGP\n`;
    body += `Expenses / المصروف: ${fmt(spent)} EGP\n`;
    body += `Net / الصافي:       ${fmtS(totInc - Math.abs(spent))} EGP\n`;
    body += `Savings / الادخار:  ${fmt(sc['save'] || 0)} EGP\n\n`;
    body += `📈 BREAKDOWN / التفصيل\n${'-'.repeat(30)}\n`;
    
    sorted.forEach(([id, amt]) => {
      const c = cats.find(cat => cat.id === id);
      if (c) {
        const p = spent > 0 ? Math.round((amt / spent) * 100) : 0;
        body += `${c.icon} ${c.en}/${c.ar}: ${fmt(amt)} EGP (${p}%)\n`;
      }
    });

    body += `\n💡 INSIGHTS / الرؤى\n${'-'.repeat(30)}\n`;
    cats.forEach(c => {
      const lim = budgets[c.id] || 0;
      const sp = sc[c.id] || 0;
      if (lim > 0 && sp > lim) body += `⚠️ ${c.en}/${c.ar}: ${Math.round(((sp - lim) / lim) * 100)}% over budget\n`;
    });

    body += `\n─────────────────────\nGenerated by Thara Finance App\nأُنشئ بواسطة تطبيق ثروة`;
    
    const sub = encodeURIComponent(`Thara Report — ${ml}`);
    const bd = encodeURIComponent(body);
    window.open(`mailto:${email || ''}?subject=${sub}&body=${bd}`);
  };

  const d = new Date();
  const ml = `${getMonthNameAr()} ${d.getFullYear()} — ${getMonthNameEn()}`;

  return (
    <div className="sc on" id="sc-rep" style={{ display: 'flex' }}>
      <div className="hdr">
        <div className="htitle">Monthly Report</div>
        <div className="hsub">{ml}</div>
      </div>
      <div id="rep-content">
        <div style={{ padding: '0 16px', marginBottom: '16px' }}>
          <div className="rstat"><span className="rstat-l">Total Income / إجمالي الدخل</span><span className="rstat-v" style={{ color: 'var(--teal)' }}>{fmt(totInc)} ج</span></div>
          <div className="rstat"><span className="rstat-l">Total Spent / إجمالي المصروف</span><span className="rstat-v" style={{ color: 'var(--red)' }}>{fmt(spent)} ج</span></div>
          <div className="rstat" style={{ background: net >= 0 ? 'var(--tealt)' : 'var(--redt)' }}>
            <span className="rstat-l" style={{ fontWeight: 700 }}>Net Balance / الرصيد الصافي</span>
            <span className="rstat-v" style={{ color: net >= 0 ? 'var(--teal)' : 'var(--red)', fontSize: '22px' }}>{fmtS(net)} ج</span>
          </div>
        </div>

        {sorted.length > 0 ? (
          <>
            <div className="card" style={{ marginBottom: '12px' }}>
              <div className="ch"><span className="ct">Spending Breakdown / تفصيل الإنفاق</span></div>
              <div className="chart-wrap"><canvas ref={chartRef}></canvas></div>
            </div>

            <div className="card">
              <div className="ch"><span className="ct">By Category / حسب الفئة</span></div>
              {sorted.map(([id, amt]) => {
                const cat = cats.find(c => c.id === id) || { en: id, ar: id, icon: '💸', c: '#888' };
                const p = spent > 0 ? Math.round((amt / spent) * 100) : 0;
                const lim = budgets[id] || 0;
                const cls = lim > 0 && amt > lim ? 'fr' : p > 30 ? 'fa' : 'ft';
                return (
                  <div key={id} className="prg">
                    <div className="prg-meta">
                      <span className="prg-name">{cat.icon} {cat.en}/{cat.ar}</span>
                      <span className="prg-nums">{fmt(amt)} ج · {p}%</span>
                    </div>
                    <div className="prg-track"><div className={`prg-fill ${cls}`} style={{ width: `${p}%` }}></div></div>
                  </div>
                );
              })}
            </div>
          </>
        ) : (
          <div className="empty" style={{ padding: '40px 16px' }}>
            <div className="empty-icon">📊</div>
            <div className="empty-text">No expenses this month<br />لا توجد مصروفات هذا الشهر</div>
          </div>
        )}

        {ins.length > 0 && (
          <>
            <div className="slabel">Behavioral Analysis / التحليل السلوكي</div>
            <div style={{ padding: '0 16px', marginBottom: '16px' }}>
              {ins.map((i, idx) => (
                <div key={idx} style={{ display: 'flex', gap: '10px', padding: '11px 14px', background: 'rgba(255,255,255,.04)', borderRadius: '11px', marginBottom: '6px', border: '0.5px solid var(--border)' }}>
                  <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: i.c, marginTop: '6px', flexShrink: 0 }}></div>
                  <div style={{ fontSize: '13px', color: 'var(--text2)', lineHeight: 1.6 }}>{i.t}</div>
                </div>
              ))}
            </div>
          </>
        )}

        <div style={{ padding: '0 16px 16px' }}>
          <button className="btns" onClick={handleExport} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', color: 'var(--gold)', borderColor: 'rgba(247,201,72,.3)' }}>
            📧 Send Report by Email / إرسال التقرير
          </button>
        </div>
      </div>
    </div>
  );
}
